global:
  scrape_interval: 2s
  evaluation_interval: 5s

scrape_configs:
  - job_name: sqs-workers
    metrics_path: /metrics
    static_configs:
      - targets:
          - worker-1:8080
          - worker-2:8080
        labels:
          app: sqs-worker
